### ISSUE TITLE
404 Page Hero Image Not Displaying

### ISSUE THREAD

**Issue by Programazing** [jhu247/minimal-academic#15]
I noticed when you go to /404.html the hero image doesn't display.

Do I need to overwrite the theme layout with a local one or is there some way to use a markdown file?

**Comment by theorangepotato** [comment]
It looks like the image link for the background image is `http://localhost:1313/img/%3Cnil%3E` (which is equivalent to `/img/<nil>`), so it seems that Hugo can't see a hero_image parameter for 404.html once it gets to `themes/minimal-academic/layouts/partials/masthead_hero.html`.

It looks like 404.html does not get page metadata, even if you create a `content/404.md`? If anyone can figure out how to do this, that might be the cleanest option. Otherwise, there are a few options:

* In the short term, yes, you can write a custom 404 layout. This might be more work to maintain, though.
* Additionally, you can modify `themes/minimal-academic/layouts/partials/masthead_hero.html` to provide a default hero_image value. Say, something like this:
```
<style type="text/css">
{{ $url := "" }}
{{ if ne ( $.Param "hero_image" ) nil }}
  {{ $url = (print "img" "/" ( $.Param "hero_image" ) ) }}
{{ else }}
  {{ $url = "/img/hero.jpg" }}
{{ end }}
.masthead-hero {
  background-image: url("{{ $url | absURL }}");
}
</style>

<div class="masthead-hero"></div>
```
*  Long term, though, I think we should add a config parameter for a default hero_image value, and have `masthead_hero.html` drop in that instead of a hard-coded one.

**Comment by Programazing** [comment]
I ended up copying the 404 to my site's layout folder then making a new partial `404_head.html` which is just a hardcoded version of `masthead_hero.html`

```
<style type="text/css">
    .masthead-hero {
      background-image: url("/img/404-Cat.jpg");
    }
</style>

<div class="masthead-hero"></div>
```

**Comment by band** [comment]
Maybe related? Hero Image does not display on Home page. It does display on other pages. Perhaps @theorangepotato solution for masthead_hero.html is the solution for this problem as well? I will be experimenting.

**Comment by Programazing** [comment]
@band If you haven't figured it out yet you can start a new issue and we'll try to help you out.

**Comment by band** [comment]
Thanks. Will do.
